trailerapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'trailerapp'
urlpatterns = [
    path('', views.FilmListView.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='trailerapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='trailerapp/logout.html'), name='logout'),
    path('get-films/', views.get_films, name='get-films'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('film/<int:pk>/', views.FilmDetailView.as_view(), name='film-detail'),
    path('genre/', views.genre, name='genre'),
    path('genre-list/<int:pk>/', views.GenreFilmListView.as_view(), name='genre-list'),
    path('data-protection/', views.data_protection, name='data-protection'),
    path('imprint/', views.imprint, name='imprint'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trailerpress/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('trailerapp.urls'), name='trailerapp'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='trailerapp/password_reset.html'),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='trailerapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='trailerapp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='trailerapp/password_reset_complete.html'),
         name='password_reset_complete'),
]

trailerapp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import ExifTags, Image


class Genre(models.Model):
    tmdb_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    __repr__ = __str__


class Film(models.Model):
    title = models.CharField(max_length=255)
    original_title = models.CharField(max_length=255, null=True)
    language = models.CharField(max_length=8, null=True)  # iso_639_1
    original_language = models.CharField(max_length=8, null=True)  # iso_639_1
    region = models.CharField(max_length=8, null=True)  # iso_3166_1
    overview = models.TextField(null=True)
    release_date = models.DateTimeField(null=True)
    tmdb_id = models.CharField(max_length=64, null=True, unique=True)
    vote_average = models.FloatField(null=True)
    vote_count = models.IntegerField(null=True)
    backdrop_path = models.CharField(max_length=255, null=True)
    poster_path = models.CharField(max_length=255, null=True)
    genre = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title

    __repr__ = __str__


class Trailer(models.Model):
    title = models.CharField(max_length=255)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    tmdb_id = models.CharField(max_length=64, null=True, unique=True)
    language = models.CharField(max_length=8, null=True)  # iso_639_1
    region = models.CharField(max_length=8, null=True)  # iso_3166_1
    site = models.CharField(max_length=64, null=True)  # origin of video
    site_key = models.CharField(max_length=64, null=True)  # key of video at origin
    type = models.CharField(max_length=10, null=True)  # Trailer|Teaser
    date_added = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

    __repr__ = __str__


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return '{} Profile'.format(self.user.username)

    __repr__ = __str__

    def save(self, force_insert=False, force_update=False, using=None):
        super().save()

        img = Image.open(self.image.path)

        try:
            for orientation in ExifTags.TAGS.keys():
                if ExifTags.TAGS[orientation] == 'Orientation':
                    break
            exif = dict(img._getexif().items())

            if exif[orientation] == 3:
                img = img.rotate(180, expand=True)
            elif exif[orientation] == 6:
                img = img.rotate(270, expand=True)
            elif exif[orientation] == 8:
                img = img.rotate(90, expand=True)
            img.save(self.image.path)
        except (AttributeError, KeyError, IndexError):
            # cases: image don't have getexif
            pass

        max_width, max_height = 300, 300

        if img.height > max_height or img.width > max_width:
            if img.height >= img.width:
                aspect_ratio = img.height / img.width
                output_size = (max_width, max_height * aspect_ratio)
            else:
                aspect_ratio = img.width / img.height
                output_size = (max_width * aspect_ratio, max_height)
            img.thumbnail(output_size)
            if img.height is not img.width:
                width, height = img.size
                left = (width - max_width) / 2
                top = (height - max_height) / 2
                right = (width + max_width) / 2
                bottom = (height + max_height) / 2
                cropped_img = img.crop((left, top, right, bottom))
                cropped_img.save(self.image.path)
        else:
            img.save(self.image.path)

        img.close()

trailerapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

trailerapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Film, Genre
from .services import save_data
from trailerpress.settings import API_KEY, LANGUAGE, REGION
from star_ratings.models import UserRating
from itertools import chain


class FilmListView(ListView):
    model = Film
    template_name = 'trailerapp/home.html'
    context_object_name = 'films'
    paginate_by = 5
    ordering = ['title']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'TrailerPress'
        return context


class FilmDetailView(DetailView):
    model = Film
    context_object_name = 'film'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'TrailerPress - Filmansicht'
        return context


def genre(request):
    context = {
        'page_title': 'TrailerPress - Suche nach Genre',
        'genres': list(set(chain.from_iterable({i.genre.all() for i in Film.objects.all() if i.genre}))),
    }
    return render(request, 'trailerapp/genre.html', context)


class GenreFilmListView(FilmListView):
    template_name = 'trailerapp/genre_list.html'

    def get_queryset(self):
        films = Film.objects.filter(genre__tmdb_id__contains=self.kwargs['pk']).order_by('title')
        return films

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.get(tmdb_id=self.kwargs['pk'])
        context['page_title'] = 'TrailerPress - Genre'
        return context


@user_passes_test(lambda u: u.is_superuser)
def get_films(request):
    api_key = API_KEY
    language = LANGUAGE
    page = 1
    region = REGION
    films = {}
    if request.GET.get('playing'):
        url = 'https://api.themoviedb.org/3/movie/now_playing'
        films = save_data(url, api_key, language, page, region)
    if request.GET.get('upcoming'):
        url = 'https://api.themoviedb.org/3/movie/upcoming'
        films = save_data(url, api_key, language, page, region)
    return render(request, 'trailerapp/get_films.html', {'films': films, 'page_title': 'TrailerPress - Get Films'})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,
                             'Benutzerkonto für {} wurde erstellt! Sie können sich nun einloggen.'.format(username))
            return redirect('trailerapp:login')
    else:
        form = UserRegisterForm()
    return render(request, 'trailerapp/register.html', {'form': form, 'page_title': 'TrailerPress - Registrierung'})


def about(request):
    return render(request, 'trailerapp/about.html', {'page_title': 'TrailerPress - Über uns'})


def data_protection(request):
    return render(request, 'trailerapp/data_protection.html', {'page_title': 'TrailerPress - Datenschutzerklärung'})


def imprint(request):
    return render(request, 'trailerapp/imprint.html', {'page_title': 'TrailerPress - Impressum'})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Ihr Benutzerkonto wurde aktualisiert!')
            return redirect('trailerapp:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'ratings': UserRating.objects.filter(user=request.user),
        'page_title': 'TrailerPress - Profil'
    }

    return render(request, 'trailerapp/profile.html', context)

trailerapp/templates/trailerapp/base.html
{% load static %}
{% load icons %}
{% load cookielaw_tags %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="UTF-8">
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'trailerapp/favicon.ico' %}">
    {# Load the tag library #}
    {% load bootstrap4 %}
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <!-- Font Awesome CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous"
    >
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'trailerapp/js/video-js.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'trailerapp/css/styles.css' %}">
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'trailerapp:home' %}">TrailerPress</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                {% if user.is_authenticated %}
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="{% url 'trailerapp:genre' %}">{% icon 'search' %}</a>
                        <a class="nav-item nav-link" href="{% url 'trailerapp:about' %}">Über uns</a>
                    </div>
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{% url 'trailerapp:profile' %}">
                            <img class="rounded-circle nav-profile-img" src="{{ user.profile.image.url }}">
                        </a>
                    </div>
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{% url 'trailerapp:logout' %}">Ausloggen</a>
                    </div>
                {% else %}
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="{% url 'trailerapp:genre' %}">{% icon 'search' %}</a>
                        <a class="nav-item nav-link" href="{% url 'trailerapp:about' %}">Über uns</a>
                        <a class="nav-item nav-link" href="{% url 'trailerapp:login' %}">Einloggen</a>
                        <a class="nav-item nav-link" href="{% url 'trailerapp:register' %}">Registrieren</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
<main class="container">
    <div class="row">
        <div class="col-md-12 col-lg-10">
            {% cookielaw_banner %}
            <div class="close-cookies"></div>
            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
<footer class="container">
    <div class="row">
        <div class="col-md-12 col-lg-10 text-center">
            <a class="col-5" href="{% url 'trailerapp:imprint' %}">Impressum</a>
            <a class="col-5" href="{% url 'trailerapp:data-protection' %}">Datenschutzerklärung</a>
        </div>
    </div>
</footer>
{% bootstrap_javascript jquery='full' %}
<script src="{% static 'cookielaw/js/cookielaw.js' %}"></script>
<script src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script src="{% static 'trailerapp/js/video.min.js' %}"></script>
<script src="{% static 'trailerapp/js/Youtube.min.js' %}"></script>
<script src="{% static 'trailerapp/js/isInViewport.min.js' %}"></script>
<script src="{% static 'trailerapp/js/helpers.js' %}"></script>
</body>
</html>

trailerapp/templates/trailerapp/film-entity.html
{% load ratings %}
<div id="tmdb-{{ film.tmdb_id }}" class="content-section">
    <h3>{{ film.title }}</h3>
    <p>Kinostart: {{ film.release_date|date }}
        {% if film.genre.all %}
            | Genre:
            {% for genre in film.genre.all %}
                <a href="{% url 'trailerapp:genre-list' genre.tmdb_id %}">
                    {{ genre }}{% if not forloop.last %},{% endif %}</a>
            {% endfor %}
        {% endif %}
    </p>
    <video
            id="yt-{{ film.trailer_set.last.site_key }}"
            class="video-js vjs-default-skin vjs-big-play-centered"
            controls
            data-setup='{
                                "techOrder": ["youtube"],
                                "sources": [{
                                    "type": "video/youtube",
                                    "src": "https://www.youtube.com/embed/{{ film.trailer_set.last.site_key }}"
                                }],
                                "fluid": true
                            }'
            {% if film.backdrop_path %}
            poster="https://image.tmdb.org/t/p/w780/{{ film.backdrop_path }}"
            {% endif %}
    ></video>
    <div class="rating-and-synopsis-section">
        {% ratings film %}
        {% if film.overview %}
            <div class="text-right synopsis-btn">
                <button class="btn btn-dark" type="button"
                        data-toggle="collapse"
                        data-target="#collapse-{{ film.tmdb_id }}"
                        aria-expanded="false"
                        aria-controls="collapse-{{ film.tmdb_id }}">
                    Synopsis
                </button>
            </div>
        {% endif %}
    </div>
    {% if film.overview %}
        <div class="collapse" id="collapse-{{ film.tmdb_id }}">
            <div class="card card-body">
                {{ film.overview }}
            </div>
        </div>
    {% endif %}
</div>

trailerapp/templates/trailerapp/film_detail.html
{% extends 'trailerapp/base.html' %}
{% load icons %}
{% load ratings %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    {% include 'trailerapp/film_entity.html' %}
{% endblock %}

trailerapp/templates/trailerapp/genre.html
{% extends 'trailerapp/base.html' %}
{% load icons %}
{% load ratings %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    {% if genres %}
        <h3>Suche nach Genre:</h3>
        {% for genre in genres %}
                <a href="{% url 'trailerapp:genre-list' genre.tmdb_id %}"><div class="content-section"><h4>{{ genre }}</h4></div></a>
        {% endfor %}
    {% else %}
        <p>No Genres found.</p>
    {% endif %}
{% endblock %}

trailerapp/templates/trailerapp/genre_list.html
{% extends 'trailerapp/base.html' %}

{% block title %}
    {{ page_title }} {{ genre.name }}
{% endblock %}

{% block content %}
    {% if films %}
        <div class="content-section"><h3>Filmgenre: {{ genre.name }}</h3></div>
        {% for film in films %}
            {% include 'trailerapp/film_entity.html' %}
        {% endfor %}
        {% include 'trailerapp/pagination.html' %}
    {% else %}
        <p>No films found.</p>
    {% endif %}
{% endblock %}

trailerapp/templates/trailerapp/imprint.html
{% extends "trailerapp/base.html" %}

{% block title %}
{{ page_title }}
{% endblock %}

{% block content %}
<div class="content-section">
    <div class='impressum'>
        <h4>Impressum</h4>
        <p>Angaben gemäß § 5 TMG</p>
        <p>
            TBD
        </p>
        <p><strong>Vertreten durch: </strong>
            TBD
        </p>
        <p><strong>Kontakt:</strong>TBD</p>
        <p><strong>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</strong>TBD
            <p><strong>Haftungsausschluss: </strong><br><br><strong>Haftung für Inhalte</strong><br><br>
                Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit
                und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß
                § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§
                8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte
                fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit
                hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den
                allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem
                Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden
                Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.<br><br><strong>Haftung für
                    Links</strong><br><br>
                Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben.
                Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der
                verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die
                verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft.
                Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche
                Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht
                zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend
                entfernen.<br><br><strong>Urheberrecht</strong><br><br>
                Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen
                Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der
                Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.
                Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
                Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte
                Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem
                auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei
                Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend
                entfernen.<br><br><strong>Datenschutz</strong><br><br>
                Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf
                unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben
                werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre
                ausdrückliche Zustimmung nicht an Dritte weitergegeben. <br>
                Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail)
                Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist
                nicht möglich. <br>
                Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur
                Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit
                ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im
                Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.<br><br>
                Link zur Datenschutzerklärung: <a class="col-5" href="{% url 'trailerapp:data-protection' %}">
                    {{ request.get_host }}{% url 'trailerapp:data-protection' %}</a><br><br><strong>Google
                    Analytics</strong><br><br>
                Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (''Google''). Google
                Analytics verwendet sog. ''Cookies'', Textdateien, die auf Ihrem Computer gespeichert werden und die
                eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten
                Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer IP-Adresse) wird an einen Server
                von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre
                Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber
                zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene
                Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen,
                sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten.
                Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Sie
                können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software
                verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche
                Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie
                sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und
                Weise und zu dem zuvor benannten Zweck einverstanden.<br><br><strong>Google AdSense</strong><br><br>
                Diese Website benutzt Google Adsense, einen Webanzeigendienst der Google Inc., USA (''Google''). Google
                Adsense verwendet sog. ''Cookies'' (Textdateien), die auf Ihrem Computer gespeichert werden und die eine
                Analyse der Benutzung der Website durch Sie ermöglicht. Google Adsense verwendet auch sog. ''Web
                Beacons'' (kleine unsichtbare Grafiken) zur Sammlung von Informationen. Durch die Verwendung des Web
                Beacons können einfache Aktionen wie der Besucherverkehr auf der Webseite aufgezeichnet und gesammelt
                werden. Die durch den Cookie und/oder Web Beacon erzeugten Informationen über Ihre Benutzung dieser
                Website (einschließlich Ihrer IP-Adresse) werden an einen Server von Google in den USA übertragen und
                dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website im Hinblick auf
                die Anzeigen auszuwerten, um Reports über die Websiteaktivitäten und Anzeigen für die Websitebetreiber
                zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene
                Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen,
                sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten.
                Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Das
                Speichern von Cookies auf Ihrer Festplatte und die Anzeige von Web Beacons können Sie verhindern, indem
                Sie in Ihren Browser-Einstellungen ''keine Cookies akzeptieren'' wählen (Im MS Internet-Explorer unter
                ''Extras > Internetoptionen > Datenschutz > Einstellung''; im Firefox unter ''Extras > Einstellungen >
                Datenschutz > Cookies''); wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht
                sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website
                erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor
                beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p><br>
            Website Impressum von <a href="https://www.impressum-generator.de">impressum-generator.de</a>
    </div>

</div>
{% endblock content %}

trailerapp/templates/trailerapp/login.html
{% extends "trailerapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    TrailerPress - Einloggen
{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Einloggen
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-dark" type="submit">Einloggen</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Passwort vergessen?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Brauchen Sie ein Benutzerkonto? <a class="ml-2" href="{% url 'trailerapp:register' %}">Jetzt registrieren.</a>
            </small>
        </div>
    </div>
{% endblock content %}